import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import { QueryProvider } from "@/components/query-provider";

const inter = Inter({subsets: ["latin"]})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={cn(inter.className, "antialiased min-h-screen")}>
        <QueryProvider>
          {children}
          <Toaster 
            position="bottom-right" 
            toastOptions={{
              duration: 4000,
              style: {
                background: '#fff',
                color: '#000',
              },
            }}
          />
        </QueryProvider>
      </body>
    </html>
  );
}
